version: "3"
services:
  nginx:
    container_name: jira_nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./resources/:/opt/jirarush/resources
    depends_on:
      - jr_server
    networks:
      - jr_network

  jr_server:
    container_name: jira_server
    image: jira_app
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080:8080"
    environment:
      db_url: ${db_url_dock}
      db_login: ${db_login}
      db_password: ${db_password}
      github_id: ${github_id}
      github_secret: ${github_secret}
      google_id: ${google_id}
      google_secret: ${google_secret}
      gitlab_id: ${gitlab_id}
      gitlab_secret: ${gitlab_secret}
      mail_login: ${mail_login}
      mail_password: ${mail_password}
      mail_starttls_enable: ${mail_starttls_enable}
      mail_auth: ${mail_auth}
      mail_host: ${mail_host}
      mail_port: ${mail_port}
    depends_on:
      - postgres
    networks:
      - jr_network

  postgres:
    container_name: jira_db
    image: postgres
    expose:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${db_login}
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_DB: jira
    networks:
      - jr_network

networks:
  jr_network:
    driver: bridge
